version: "3.9"

networks:
    backend:
        external: true

services:
  postgres_db:
    container_name: postgresdb
    image: postgres:13

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "dvdrental"
    ports:
      - "5432:5432"
    networks:
      - "backend"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_seed:
      container_name: postgresseed
      image: postgres:13
      environment:
          POSTGRES_HOST_AUTH_METHOD: "trust"
          PGPASSWORD: "1234"
      volumes:
          - ./postgres/dvdrental.tar:/tmp/dvdrental.tar:ro
      entrypoint: [ "bash", "-c", "sleep 10 && pg_restore -h postgresdb -U postgres -d dvdrental /tmp/dvdrental.tar" ]
      restart: "no"
      networks:
        - "backend"
      depends_on:
        - "postgres_db"


  adminer:
    container_name: adminer
    image: adminer
    networks:
      - "backend"
    ports:
      - "${UI_PORT?}:8080"

  arangodb:
    container_name: arangodb
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
        - "8529:8529"
    networks:
        - "backend"
    depends_on:
        - "postgres_seed"
  
  script:
    container_name: script
    build: .
    depends_on:
      postgres_db:
        condition: service_healthy
      arangodb:
        condition: service_started
    networks:
        - "backend"